import Head from 'next/head'
import { useEffect, useRef } from "react"
import Image from 'next/image'
import Contato from '../components/MyContato'
import Navigation from '../components/MyNavigation'
import MySection from '../components/MySection'
import styles from '../styles/Home.module.scss'
import { BrowserRouter } from 'react-router-dom'
import About from "../components/MyAbout"
import Skill from '../components/MySkills'
import Project from '../components/Projects'

export default function Home() {
  const section1 = useRef();
  const section2 = useRef();
  const section3 = useRef();

  function scrollTo(section){
    section.current.scrollIntoView({ behaivor: "smooth"});
  }
  return (
    <div className={`container ${styles.container}`}>
      <Head>
        <title>Portfólio | Adimar Sarkis</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
        <Navigation 
          sobre={section1}
          habilidades={section2}
          projetos={section3}
        />
        <div ref={section1}>
          <MySection
            headline={`ABOUT`}
            scrollTo={scrollTo} 
            goToSectionRef={section2}
            showArrow={true}
            />
          <About />
        </div>
        <div ref={section2}>
          <MySection
            image={"/imagens/1202299.jpg"}
            headline={`SKILLS`}
            scrollTo={scrollTo}
            goToSectionRef={section3}
            showArrow={true} />
            <Skill />
        </div>
        <div ref={section3}> 
          <MySection
            headline={`PROJECTS`}
            showArrow={false} />
            <Project
              imageBox1={'/imagens/austin-neill-Be7DMcK7k3o-unsplash.jpg'}
              nomeBox1={"Lorem ispuls"}
              descricaoBox1={"Lorem Lorem Lorem Lorem Lorem Lorem"}
              nomeBox2={"Lorem ispuls"}
              descricaoBox2={"Lorem Lorem Lorem Lorem Lorem Lorem"}
              nomeBox3={"Lorem ispuls"}
              descricaoBox3={"Lorem Lorem Lorem Lorem Lorem Lorem"}
              nomeBox4={"Lorem ispuls"}
              descricaoBox4={"Lorem Lorem Lorem Lorem Lorem Lorem"}
              nomeBox5={"Lorem ispuls"}
              descricaoBox5={"Lorem Lorem Lorem Lorem Lorem Lorem"}
              />
            
        </div>
        <Contato />
      
    </div>
  )
}
