import Head from 'next/head'
import { useEffect, useRef } from "react"
import Image from 'next/image'
import Contato from '../components/contato'
import Navigation from '../components/navigation'
import MySection from '../components/MySection'
import styles from '../styles/Home.module.scss'
import { BrowserRouter } from 'react-router-dom'
import About from "../components/about"


export default function Home() {
  const section1 = useRef();
  const section2 = useRef();
  const section3 = useRef();

  function scrollTo(section){
    section.current.scrollIntoView({ behaivor: "smooth"});
  }
  return (
    <div className={`container ${styles.container}`}>
      <Head>
        <title>Portifolio | Adimar Sarkis</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
        <Navigation 
          sobre={section1}
          habilidades={section2}
          projetos={section3}
        />
        <div ref={section1}>
          <MySection
            headline={`SOBRE`}
            scrollTo={scrollTo} 
            goToSectionRef={section2}
            showArrow={true}
            />
          <About />
        </div>
        <div ref={section2}>
          <MySection
            image={"/imagens/1202299.jpg"}
            headline={`HABILIDADES`}
            scrollTo={scrollTo}
            goToSectionRef={section3}
            showArrow={true} />
        </div>
        <div ref={section3}> 
          <MySection
           
            headline={`PROJETOS`}
            showArrow={false} />
        </div>
        <Contato />
      
    </div>
  )
}
