import Head from 'next/head'
import { useRef } from "react"
import Contato from '../src/components/MyContato'
import Navigation from '../src/components/MyNavigation'
import MySection from '../src/components/MySection'
import styles from '../src/styles/Home.module.scss'
import About from "../src/components/MyAbout"
import Skill from '../src/components/MySkills'
import Project from '../src/components/Projects'

export default function Home() {
  const section1 = useRef();
  const section2 = useRef();
  const section3 = useRef();

  function scrollTo(section){
    section.current.scrollIntoView({ behaivor: "smooth"});
  }
  return (
    <div className={`container ${styles.container}`}>
      <Head>
        <title>Portfólio | Adimar Sarkis</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/faviconCruz.ico" />
      </Head>

        <Navigation 
          sobre={section1}
          habilidades={section2}
          projetos={section3}
        />
        <div ref={section1}>
          <MySection
            headline={`ABOUT`}
            scrollTo={scrollTo} 
            goToSectionRef={section2}
            showArrow={true}
            />
          <About />
        </div>
        <div ref={section2}>
          <MySection
            image={"/imagens/1202299.jpg"}
            headline={`SKILLS`}
            scrollTo={scrollTo}
            goToSectionRef={section3}
            showArrow={true} />
            <Skill />
        </div>
        <div ref={section3}> 
          <MySection
            headline={`PROJECTS`}
            showArrow={false} />
            <Project/>
        </div>
        <Contato />
      
    </div>
  )
}
